### ISSUE TITLE
Failed to build because of html2canvas was gone.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [CounterpartyXCP/counterwallet#852]
Looks repository git://github.com/xnova/html2canvas.git was removed. How to fix?

```
  "id": "ECMDERR",
  "level": "error",
  "message": "Failed to execute \"git clone git://github.com/xnova/html2canvas.git /counterwallet/2a0f06b033002a90a3a8300e04d00100/bower/571165aba94fc09db750c0c3b9e5926d-19-Ua3F7x --progress\", exit code of #128\nCloning into '/counterwallet/2a0f06b033002a90a3a8300e04d00100/bower/571165aba94fc09db750c0c3b9e5926d-19-Ua3F7x'...\nfatal: remote error: \n  Repository not found.\n",
  "stacktrace": "Error: Failed to execute \"git clone git://github.com/xnova/html2canvas.git /counterwallet/2a0f06b033002a90a3a8300e04d00100/bower/571165aba94fc09db750c0c3b9e5926d-19-Ua3F7x --progress\", exit code of #128\nCloning into '/counterwallet/2a0f06b033002a90a3a8300e04d00100/bower/571165aba94fc09db750c0c3b9e5926d-19-Ua3F7x'...\nfatal: remote error: \n  Repository not found.\n\n    at createError (/counterwallet/node_modules/bower/lib/util/createError.js:4:15)\n    at ChildProcess.<anonymous> (/counterwallet/node_modules/bower/lib/util/cmd.js:102:21)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:862:16)\n    at Socket.<anonymous> (internal/child_process.js:338:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:490:12)"
}]
```

**Comment by cryptcoin-junkey** [comment]
It looks this issue was resolved. I close this.
